---
deployment:
  tasks:
    # 1. Define deployment path
    - export DEPLOY_PATH=/home/mvpmyriam/repositories/ecoReport-itos-packed

    # 2. Move to the deployment directory
    - cd $DEPLOY_PATH

    # 3. Install Composer dependencies
    - composer install --no-interaction --prefer-dist --optimize-autoloader

    # 4. Install Node.js dependencies (if your backend uses assets managed by npm/yarn)
    - cd backend
    - npm install
    - cd ..

    # 5. Run Yii migrations
    - php yii migrate --interactive=0

    # 6. Clear application cache
    - php yii cache/flush-all

    # 7. Set file permissions
    - chmod -R 755 runtime backend/web/assets console yii
