---
deployment:
  tasks:
    # Define deployment path
    - export DEPLOY_PATH=/home/mvpmyriam/repositories/ecoReport-itos-packed

    # Go to deploy directory
    - cd $DEPLOY_PATH

    # Pull latest changes (optional if auto-deploy is already on)
    - git pull

    # Install Composer dependencies
    - composer install --no-interaction --prefer-dist --optimize-autoloader

    # Install Node.js dependencies
    - npm install

    # Run Yii console setup (migrations)
    - yes | php console/yii app/setup

    # Set proper permissions
    - chmod -R 775 backend/runtime backend/web/assets storage
